### ISSUE TITLE
bigbang-cli存在占用CPU高的问题

### ISSUE THREAD

**Issue by cchanm** [bigbangcore/BigBang#480]
通过SSH登录到服务器，开启bigbang-cli，并执行一些命令，然后关闭SSH的窗口，即不退出bigbang-cli的情况下，关闭SSH的窗口，再SSH登录到服务器，可以看到bigbang-cli占用CPU高，大概为一个线程的100%。

**Comment by AlexiaChen** [comment]
这个我先用本机ssh模拟下，昆明这边的测试服暂时上不去。

**Comment by AlexiaChen** [comment]
先把gdb的分析结果弄上来:

```gdb
 sudo gdb attach 10820
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: No such file or directory.
Attaching to process 10820
[New LWP 10821]
[New LWP 10822]
[New LWP 10823]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcc192988) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88      ../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) bt
#0  0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcc192988) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55bdcc192938, cond=0x55bdcc192960) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55bdcc192960, mutex=0x55bdcc192938) at pthread_cond_wait.c:655
#3  0x000055bdca6f4701 in boost::condition_variable::wait (this=0x55bdcc192938, m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:81
#4  0x000055bdca8b3fb3 in boost::thread::join_noexcept() ()
#5  0x000055bdca8437f6 in boost::thread::join (this=0x55bdcc1928c0) at /usr/include/boost/thread/detail/thread.hpp:775
#6  0x000055bdca843858 in xengine::CThread::Exit (this=0x55bdcc190960) at /home/ubuntu/BigBang/src/bigbang/../xengine/docker/thread.h:50
#7  0x000055bdcaa7b55a in xengine::CDocker::ThreadExit (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:371
#8  0x000055bdcaa75c5e in xengine::IBase::ThreadExit (this=0x55bdcc1907f0, thr=...) at /home/ubuntu/BigBang/src/xengine/base/base.cpp:205
#9  0x000055bdca72205d in bigbang::CRPCClient::HandleHalt (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/bigbang/rpcclient.cpp:99
#10 0x000055bdcaa75573 in xengine::IBase::Halt (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/xengine/base/base.cpp:101
#11 0x000055bdcaa7ae1e in xengine::CDocker::Halt (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, vWorkQueue=std::vector of length 2, capacity 2 = {...})
    at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:261
#12 0x000055bdcaa7abec in xengine::CDocker::Halt (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:226
#13 0x000055bdcaa7af90 in xengine::CDocker::Exit (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:288
#14 0x000055bdca6e5fb4 in bigbang::CBbEntry::Exit (this=0x55bdcb3b0700 <bigbang::CBbEntry::GetInstance()::entry>) at /home/ubuntu/BigBang/src/bigbang/entry.cpp:461
#15 0x000055bdca625b61 in main (argc=1, argv=0x7ffcd1435fe8) at /home/ubuntu/BigBang/src/bigbang/bigbang.cpp:37
(gdb) bt
#0  0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcc192988) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55bdcc192938, cond=0x55bdcc192960) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55bdcc192960, mutex=0x55bdcc192938) at pthread_cond_wait.c:655
#3  0x000055bdca6f4701 in boost::condition_variable::wait (this=0x55bdcc192938, m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:81
#4  0x000055bdca8b3fb3 in boost::thread::join_noexcept() () at /usr/include/boost/throw_exception.hpp:69
#5  0x000055bdca8437f6 in boost::thread::join (this=0x55bdcc1928c0) at /usr/include/boost/thread/detail/thread.hpp:775
#6  0x000055bdca843858 in xengine::CThread::Exit (this=0x55bdcc190960) at /home/ubuntu/BigBang/src/bigbang/../xengine/docker/thread.h:50
#7  0x000055bdcaa7b55a in xengine::CDocker::ThreadExit (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:371
#8  0x000055bdcaa75c5e in xengine::IBase::ThreadExit (this=0x55bdcc1907f0, thr=...) at /home/ubuntu/BigBang/src/xengine/base/base.cpp:205
#9  0x000055bdca72205d in bigbang::CRPCClient::HandleHalt (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/bigbang/rpcclient.cpp:99
#10 0x000055bdcaa75573 in xengine::IBase::Halt (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/xengine/base/base.cpp:101
#11 0x000055bdcaa7ae1e in xengine::CDocker::Halt (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, vWorkQueue=std::vector of length 2, capacity 2 = {...})
    at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:261
#12 0x000055bdcaa7abec in xengine::CDocker::Halt (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:226
#13 0x000055bdcaa7af90 in xengine::CDocker::Exit (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:288
#14 0x000055bdca6e5fb4 in bigbang::CBbEntry::Exit (this=0x55bdcb3b0700 <bigbang::CBbEntry::GetInstance()::entry>) at /home/ubuntu/BigBang/src/bigbang/entry.cpp:461
#15 0x000055bdca625b61 in main (argc=1, argv=0x7ffcd1435fe8) at /home/ubuntu/BigBang/src/bigbang/bigbang.cpp:37
(gdb) info threads
  Id   Target Id         Frame
* 1    Thread 0x7fa23fc6d780 (LWP 10820) "bigbang-cli" 0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcc192988)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  2    Thread 0x7fa23e905700 (LWP 10821) "Docker_Timer" 0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x55bdcb3b0978 <bigbang::CBbEntry::GetInstance()::entry+632>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fa23e104700 (LWP 10822) "httpget" 0x00007fa23ea27bb7 in epoll_wait (epfd=9, events=0x7fa23e1033d0, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  4    Thread 0x7fa23d903700 (LWP 10823) "rpcclient" 0x00007fa23e94514d in __GI___sigprocmask (how=0, set=0x0, oset=0x7fa23d902970) at ../sysdeps/unix/sysv/linux/x86_64/sigprocmask.c:36
(gdb) thread 3
[Switching to thread 3 (Thread 0x7fa23e104700 (LWP 10822))]
#0  0x00007fa23ea27bb7 in epoll_wait (epfd=9, events=0x7fa23e1033d0, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30      ../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory.
(gdb) bt
#0  0x00007fa23ea27bb7 in epoll_wait (epfd=9, events=0x7fa23e1033d0, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x000055bdcaa6ce3d in boost::asio::detail::epoll_reactor::run (this=0x55bdcc190680, block=true, ops=...) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:438
#2  0x000055bdcaa6e319 in boost::asio::detail::task_io_service::do_run_one (this=0x55bdcc18f7d0, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:356
#3  0x000055bdcaa6de4b in boost::asio::detail::task_io_service::run (this=0x55bdcc18f7d0, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:149
#4  0x000055bdcaa6e65c in boost::asio::io_service::run (this=0x55bdcc18fb60) at /usr/include/boost/asio/impl/io_service.ipp:59
#5  0x000055bdcaa89d2d in xengine::CIOProc::IOThreadFunc (this=0x55bdcc18fad0) at /home/ubuntu/BigBang/src/xengine/netio/ioproc.cpp:315
#6  0x000055bdcaa96fe9 in boost::_mfi::mf0<void, xengine::CIOProc>::operator() (this=0x55bdcc18fb40, p=0x55bdcc18fad0) at /usr/include/boost/bind/mem_fn_template.hpp:49
#7  0x000055bdcaa960c3 in boost::_bi::list1<boost::_bi::value<xengine::CIOProc*> >::operator()<boost::_mfi::mf0<void, xengine::CIOProc>, boost::_bi::list0> (this=0x55bdcc18fb50, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:259
#8  0x000055bdcaa95060 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, xengine::CIOProc>, boost::_bi::list1<boost::_bi::value<xengine::CIOProc*> > >::operator() (this=0x55bdcc18fb40)
    at /usr/include/boost/bind/bind.hpp:1294
#9  0x000055bdcaa93d97 in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, boost::_mfi::mf0<void, xengine::CIOProc>, boost::_bi::list1<boost::_bi::value<xengine::CIOProc*> > >, void
>::invoke (function_obj_ptr=...) at /usr/include/boost/function/function_template.hpp:159
#10 0x000055bdcaa7ec59 in boost::function0<void>::operator() (this=0x55bdcc18fb38) at /usr/include/boost/function/function_template.hpp:759
#11 0x000055bdcaa7b5ca in xengine::CDocker::ThreadRun (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:381
#12 0x000055bdcaa7b764 in xengine::CDocker::ThreadDelayRun (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:412
#13 0x000055bdcaa86e81 in boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>::operator() (this=0x55bdcc192738, p=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, a1=...)
    at /usr/include/boost/bind/mem_fn_template.hpp:165
#14 0x000055bdcaa86d62 in boost::_bi::list2<boost::_bi::value<xengine::CDocker*>, boost::reference_wrapper<xengine::CThread> >::operator()<boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>, boost::_b
i::list0> (this=0x55bdcc192748, f=..., a=...) at /usr/include/boost/bind/bind.hpp:319
#15 0x000055bdcaa86c70 in boost::_bi::bind_t<void, boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>, boost::_bi::list2<boost::_bi::value<xengine::CDocker*>, boost::reference_wrapper<xengine::CThread
> > >::operator() (this=0x55bdcc192738) at /usr/include/boost/bind/bind.hpp:1294
#16 0x000055bdcaa86c00 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>, boost::_bi::list2<boost::_bi::value<xengine::CDocker*>, boost::referen
ce_wrapper<xengine::CThread> > > >::run (this=0x55bdcc192580) at /usr/include/boost/thread/detail/thread.hpp:116
#17 0x000055bdca8b3e32 in thread_proxy () at /usr/include/boost/throw_exception.hpp:69
#18 0x00007fa23f8416db in start_thread (arg=0x7fa23e104700) at pthread_create.c:463
#19 0x00007fa23ea2788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) thread 1
[Switching to thread 1 (Thread 0x7fa23fc6d780 (LWP 10820))]
#0  0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcc192988) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88      ../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) bt
#0  0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcc192988) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55bdcc192938, cond=0x55bdcc192960) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55bdcc192960, mutex=0x55bdcc192938) at pthread_cond_wait.c:655
#3  0x000055bdca6f4701 in boost::condition_variable::wait (this=0x55bdcc192938, m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:81
#4  0x000055bdca8b3fb3 in boost::thread::join_noexcept() () at /usr/include/boost/throw_exception.hpp:69
#5  0x000055bdca8437f6 in boost::thread::join (this=0x55bdcc1928c0) at /usr/include/boost/thread/detail/thread.hpp:775
#6  0x000055bdca843858 in xengine::CThread::Exit (this=0x55bdcc190960) at /home/ubuntu/BigBang/src/bigbang/../xengine/docker/thread.h:50
#7  0x000055bdcaa7b55a in xengine::CDocker::ThreadExit (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:371
#8  0x000055bdcaa75c5e in xengine::IBase::ThreadExit (this=0x55bdcc1907f0, thr=...) at /home/ubuntu/BigBang/src/xengine/base/base.cpp:205
#9  0x000055bdca72205d in bigbang::CRPCClient::HandleHalt (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/bigbang/rpcclient.cpp:99
#10 0x000055bdcaa75573 in xengine::IBase::Halt (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/xengine/base/base.cpp:101
#11 0x000055bdcaa7ae1e in xengine::CDocker::Halt (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, vWorkQueue=std::vector of length 2, capacity 2 = {...})
    at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:261
#12 0x000055bdcaa7abec in xengine::CDocker::Halt (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:226
#13 0x000055bdcaa7af90 in xengine::CDocker::Exit (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:288
#14 0x000055bdca6e5fb4 in bigbang::CBbEntry::Exit (this=0x55bdcb3b0700 <bigbang::CBbEntry::GetInstance()::entry>) at /home/ubuntu/BigBang/src/bigbang/entry.cpp:461
#15 0x000055bdca625b61 in main (argc=1, argv=0x7ffcd1435fe8) at /home/ubuntu/BigBang/src/bigbang/bigbang.cpp:37
(gdb) thread 2
[Switching to thread 2 (Thread 0x7fa23e905700 (LWP 10821))]
#0  0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcb3b0978 <bigbang::CBbEntry::GetInstance()::entry+632>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88      in ../sysdeps/unix/sysv/linux/futex-internal.h
(gdb) bt
#0  0x00007fa23f8479f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55bdcb3b0978 <bigbang::CBbEntry::GetInstance()::entry+632>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55bdcb3b0928 <bigbang::CBbEntry::GetInstance()::entry+552>, cond=0x55bdcb3b0950 <bigbang::CBbEntry::GetInstance()::entry+592>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55bdcb3b0950 <bigbang::CBbEntry::GetInstance()::entry+592>, mutex=0x55bdcb3b0928 <bigbang::CBbEntry::GetInstance()::entry+552>) at pthread_cond_wait.c:655
#3  0x000055bdca6f4701 in boost::condition_variable::wait (this=0x55bdcb3b0928 <bigbang::CBbEntry::GetInstance()::entry+552>, m=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:81
#4  0x000055bdcaa7c351 in xengine::CDocker::TimerProc (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:570
#5  0x000055bdcaa86efb in boost::_mfi::mf0<void, xengine::CDocker>::operator() (this=0x55bdcc18eee8, p=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>)
    at /usr/include/boost/bind/mem_fn_template.hpp:49
#6  0x000055bdcaa86db9 in boost::_bi::list1<boost::_bi::value<xengine::CDocker*> >::operator()<boost::_mfi::mf0<void, xengine::CDocker>, boost::_bi::list0> (this=0x55bdcc18eef8, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:259
#7  0x000055bdcaa86cd8 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, xengine::CDocker>, boost::_bi::list1<boost::_bi::value<xengine::CDocker*> > >::operator() (this=0x55bdcc18eee8)
    at /usr/include/boost/bind/bind.hpp:1294
#8  0x000055bdcaa86c22 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, xengine::CDocker>, boost::_bi::list1<boost::_bi::value<xengine::CDocker*> > > >::run (this=0x55bdcc18ed30)
    at /usr/include/boost/thread/detail/thread.hpp:116
#9  0x000055bdca8b3e32 in thread_proxy () at /usr/include/boost/throw_exception.hpp:69
#10 0x00007fa23f8416db in start_thread (arg=0x7fa23e905700) at pthread_create.c:463
#11 0x00007fa23ea2788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) thread 4
[Switching to thread 4 (Thread 0x7fa23d903700 (LWP 10823))]
#0  0x00007fa23e94514d in __GI___sigprocmask (how=0, set=0x0, oset=0x7fa23d902970) at ../sysdeps/unix/sysv/linux/x86_64/sigprocmask.c:36
36      ../sysdeps/unix/sysv/linux/x86_64/sigprocmask.c: No such file or directory.
(gdb) bt
#0  0x00007fa23e94514d in __GI___sigprocmask (how=0, set=0x0, oset=0x7fa23d902970) at ../sysdeps/unix/sysv/linux/x86_64/sigprocmask.c:36
#1  0x000055bdcaa24e59 in rl_getc () at /usr/include/boost/throw_exception.hpp:69
#2  0x000055bdcaa25754 in rl_read_key () at /usr/include/boost/throw_exception.hpp:69
#3  0x000055bdcaa2fed7 in readline_internal_char () at /usr/include/boost/throw_exception.hpp:69
#4  0x000055bdcaa25f8d in rl_callback_read_char () at /usr/include/boost/throw_exception.hpp:69
#5  0x000055bdca723a1a in bigbang::CRPCClient::LaunchConsole (this=0x55bdcc1907f0) at /home/ubuntu/BigBang/src/bigbang/rpcclient.cpp:293
#6  0x000055bdca72bbcf in boost::_mfi::mf0<void, bigbang::CRPCClient>::operator() (this=0x55bdcc190998, p=0x55bdcc1907f0) at /usr/include/boost/bind/mem_fn_template.hpp:49
#7  0x000055bdca72adcd in boost::_bi::list1<boost::_bi::value<bigbang::CRPCClient*> >::operator()<boost::_mfi::mf0<void, bigbang::CRPCClient>, boost::_bi::list0> (this=0x55bdcc1909a8, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:259
#8  0x000055bdca729b8c in boost::_bi::bind_t<void, boost::_mfi::mf0<void, bigbang::CRPCClient>, boost::_bi::list1<boost::_bi::value<bigbang::CRPCClient*> > >::operator() (this=0x55bdcc190998)
    at /usr/include/boost/bind/bind.hpp:1294
#9  0x000055bdca728bad in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<void, boost::_mfi::mf0<void, bigbang::CRPCClient>, boost::_bi::list1<boost::_bi::value<bigbang::CRPCClient*> > >
, void>::invoke (function_obj_ptr=...) at /usr/include/boost/function/function_template.hpp:159
#10 0x000055bdcaa7ec59 in boost::function0<void>::operator() (this=0x55bdcc190990) at /usr/include/boost/function/function_template.hpp:759
#11 0x000055bdcaa7b5ca in xengine::CDocker::ThreadRun (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:381
#12 0x000055bdcaa7b764 in xengine::CDocker::ThreadDelayRun (this=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, thr=...) at /home/ubuntu/BigBang/src/xengine/docker/docker.cpp:412
#13 0x000055bdcaa86e81 in boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>::operator() (this=0x55bdcc192a98, p=0x55bdcb3b0798 <bigbang::CBbEntry::GetInstance()::entry+152>, a1=...)
    at /usr/include/boost/bind/mem_fn_template.hpp:165
#14 0x000055bdcaa86d62 in boost::_bi::list2<boost::_bi::value<xengine::CDocker*>, boost::reference_wrapper<xengine::CThread> >::operator()<boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>, boost::_b
i::list0> (this=0x55bdcc192aa8, f=..., a=...) at /usr/include/boost/bind/bind.hpp:319
#15 0x000055bdcaa86c70 in boost::_bi::bind_t<void, boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>, boost::_bi::list2<boost::_bi::value<xengine::CDocker*>, boost::reference_wrapper<xengine::CThread
> > >::operator() (this=0x55bdcc192a98) at /usr/include/boost/bind/bind.hpp:1294
#16 0x000055bdcaa86c00 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, xengine::CDocker, xengine::CThread&>, boost::_bi::list2<boost::_bi::value<xengine::CDocker*>, boost::referen
ce_wrapper<xengine::CThread> > > >::run (this=0x55bdcc1928e0) at /usr/include/boost/thread/detail/thread.hpp:116
#17 0x000055bdca8b3e32 in thread_proxy () at /usr/include/boost/throw_exception.hpp:69
#18 0x00007fa23f8416db in start_thread (arg=0x7fa23d903700) at pthread_create.c:463
#19 0x00007fa23ea2788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by AlexiaChen** [comment]
通过gdb已经打开定位出占用CPU 100%的代码片段了。正在研究修改方式。

```cpp
void CRPCClient::LaunchConsole()
{
    EnterLoop();

    fd_set fs;
    timeval timeout;
    while (true)
    {
        FD_ZERO(&fs);
        FD_SET(STDIN_FILENO, &fs);

        timeout.tv_sec = 0;
        timeout.tv_usec = 100000;
        int ret = select(1, &fs, nullptr, nullptr, &timeout);
        if (ret == -1)
        {
            cerr << "select error" << endl;
        }
        else if (ret == 0)
        {
            try
            {
                boost::this_thread::interruption_point();
            }
            catch (const boost::thread_interrupted&)
            {
                break;
            }
        }
        else
        {
            rl_callback_read_char();
        }
    }

    LeaveLoop();
}
```
