### ISSUE TITLE
httpget模块crash

### ISSUE THREAD

**Issue by AlexiaChen** [bigbangcore/BigBang#91]
环境： ubuntu 18.04

gdb 栈：

```txt
0x00005555565bbcc0 in xengine::CIOClient::Close (this=0x7ffff0000e10)
    at /home/mathxh/bigbang-project/bigbang/src/xengine/netio/ioclient.cpp:62
62	    if (IsSocketOpen())
(gdb) bt
#0  0x00005555565bbcc0 in xengine::CIOClient::Close (
    this=0x7ffff0000e10)
    at /home/mathxh/bigbang-project/bigbang/src/xengine/netio/ioclient.cpp:62
#1  0x00005555565b0309 in xengine::CHttpGetClient::~CHttpGetClient (
    this=0x7ffff0001c20, __in_chrg=<optimized out>)
    at /home/mathxh/bigbang-project/bigbang/src/xengine/http/httpget.cpp:35
#2  0x00005555565b328c in xengine::CHttpGet::CloseConn (
    this=0x555556f18290, pGetClient=0x7ffff0001c20, nErrCode=-8)
    at /home/mathxh/bigbang-project/bigbang/src/xengine/http/httpget.cpp:490
#3  0x00005555565b1b47 in xengine::CHttpGet::LeaveLoop (
    this=0x555556f18290)
    at /home/mathxh/bigbang-project/bigbang/src/xengine/http/httpget.cpp:264
#4  0x00005555565b8a71 in xengine::CIOActor::HandlerThreadFunc (
    this=0x555556f18290)
---Type <return> to continue, or q <return> to quit---
    at /home/mathxh/bigbang-project/bigbang/src/xengine/message/actor.cpp:88
```

复现步骤（必现）：

- 启动bigbang
- 停止bigbang bigbang stop

**Comment by AlexiaChen** [comment]
Mac OS 环境下是，DispathEvent的栈上的事件对象被提前销毁，原因是线程被提前唤醒，Handler线程还继续访问了销毁的对象。与ubuntu环境的崩溃不一致

**Comment by AlexiaChen** [comment]
因为改成了消息模式，暂时复现不出来了，暂时关闭。
